#第一题
name="sulin"
age=30
height=175
is_student=True
print(type(name))
print(type(age))
print(type(height))
print(type(is_student))
#第二题
weight=60
height=1.75
bmi=weight/height**2
print(bmi)
#第三题
first="你好"
name="素林"
print(first+". "+name)
#第四题
first="你好"
name="素林"
print(f'{first},{name}')
#第五题
name="sulin"
age=30
height=175
weight=80
print(f'我叫{name},今年{age}岁,身高{height}厘米,体重{weight}公斤')
#第六题
pi=3.1415926
print(f'{pi:.2f}')
#第七题
pass_rate=0.873
print(f'{pass_rate:.1%}')
#第八题
n="tom"
a=25
print(f'|{n:<6}|{a:>4}|')
#第九题1
name="素林"
age=30
print("我叫"+ name+'，'+str(age) +"岁")
#第九题2
weight=65
targht=55
a=(weight-targht)
print(f'还差{a:.1f}公斤到目标')
#第十题
name="素林"
weight=65
height=1.75
target=55
print('素林当前体重'+str(weight) +'公斤')
print(f'素林距离目标还差{weight-target:.1f}公斤')
bmi=weight/height**2
print(f'素林的bmi是{bmi:.1f}')